### ISSUE TITLE
Compute tasks in parallel

### ISSUE THREAD

**Issue by jqmp** [square/bionic#43]
Currently Bionic computes tasks one at a time.  We should be able to use something like `multiprocessing` to run multiple tasks in parallel (when their dependency structure allows it).  This could provide a big speedup for flows using a lot of multiplicity.  It's also a first step towards distributed task computation.

There shouldn't be any major architectural obstacles here, since Bionic already manages an explicit stack of tasks. However, there will probably be lots of pickling edge cases to consider.

**Comment by namanjain** [comment]
Parallel execution was released as part of the 0.8.0 release. 

https://bionic.readthedocs.io/en/stable/concepts.html#parallel-execution
https://github.com/square/bionic/releases/tag/v0.8.0
https://bionic.readthedocs.io/en/stable/release-notes.html
