### ISSUE TITLE
Add tooltips to DAG visualization

### ISSUE THREAD

**Issue by jqmp** [square/bionic#56]
Currently the `Flow.render_dag()` method returns a PNG image, which doesn't support tooltips or any other kind of interaction.  However, it would be fairly straightforward to return an SVG image instead, in which case we could include tooltips for each node in the DAG.  These tooltips would be a good place to show the docstring of the corresponding entity (once [docstring integration](https://github.com/square/bionic/issues/17) is complete).

**Comment by lexi-squid-ding** [comment]
@jqmp I started looking into this and looks like as of today, [Pillow does not support SVG](
https://github.com/python-pillow/Pillow/issues/1146). But it's straightforward to get a SVG from a pydot graph, so we can evaluate additional packages like Cairo and svglib to actually render the image. 

Let me know if you have a preference

**Comment by jqmp** [comment]
Oh, good point. I'm cool with adding a dependency if necessary. That said, it seems to me that we want to support two main use cases:

    # Saving to a file.
    flow.render_dag(format='svg').save('my_dag.svg')

    # Inside a Jupyter notebook, this should render the image.
    flow.render_dag(format='svg')

I don't know offhand if those libraries provide a class that supports both of those. However, since Jupyter [knows how to render SVGs already](https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display), it would probably be easy to define our own `SvgImage` class that implements `save` and `_repr_svg_` methods. What do you think?

**Comment by lexi-squid-ding** [comment]
Will look into whether either library does this natively, otherwise adding the new class makes sense to me.
