### ISSUE TITLE
Allow caching to be globally disabled for a flow

### ISSUE THREAD

**Issue by jqmp** [square/bionic#60]
It would be nice to be able to disable all persistent caching for an existing flow.  This can be useful either to save the time of saving/loading files, or to avoid creating garbage files that need to be cleaned up.

Maybe it would look something like this:

    flow.setting('core__persistent_cache__enabled', False).get(...)

**Comment by namanjain** [comment]
We opted to disable in-memory caching by default instead, which was as part of 0.8.0 release.

https://bionic.readthedocs.io/en/v0.8.0/concepts.html#disabling-in-memory-caching
https://github.com/square/bionic/releases/tag/v0.8.0
https://bionic.readthedocs.io/en/stable/release-notes.html

**Comment by namanjain** [comment]
After further discussion, we added an option to disable persistent caching by default, which was merged in #206.
