### ISSUE TITLE
Confusing error message when serializing a dataframe with duplicate column names

### ISSUE THREAD

**Issue by jqmp** [square/bionic#7]
When serializing a dataframe with duplicate column names, Bionic produces a cryptic error message:

```
import pandas as pd
import bionic as bn

builder = bn.FlowBuilder('fail')

@builder
def frame():
    return pd.DataFrame(columns=['a', 'b', 'a'], data=[[1,2,3]])

print(builder.build().get('frame'))
```

```
...
  File "/Users/janek/Development/bionic/bionic/protocols.py", line 207, in <listcomp>
    if df[col].dtype.name == 'category'
...
AttributeError: 'DataFrame' object has no attribute 'dtype'
```

This is because `df[col]` is returning a dataframe (not a column as expected).  We should fix this to either serialize the frame correctly or generate a more helpful error message.

**Comment by bclayman** [comment]
I can't imagine many scenarios where the user would want multiple columns of the same name.  So I think checking for duplicate column names and providing a better error message is a good approach here.  Will give it a whirl!

**Comment by jqmp** [comment]
Resolved in https://github.com/square/bionic/pull/18.  Thanks @bclayman!
